version: '2'
services:
  db:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: stocks
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stocks
      PGDATA: /var/lib/postgresql/data/stocks
    volumes:
      - ./.data:/var/lib/postgresql/data/stocks
    ports:
      - 5432:5432
  mq:
    image: rabbitmq:3.6.10-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: stock
    ports:
      - 15672:15672
      - 5672:5672
  proxy:
    image: mattes/rotating-proxy
    ports:
      - 5566:5566
      - 4444:4444
    environment:
      tor: 25
  worker:
    build: .
    command: celery -A stock_scraper.tasks worker --loglevel=debug
    volumes:
      - .:/usr/src/stock-scaper
    depends_on:
      - db
      - mq
      - proxy
    env_file: .env
    environment:
      DATABASE_URL: postgres://stocks:password@db:5432/stocks
      RABBITMQ_URL: amqp://rabbit:stock@mq:5672
      GOOGLE_CREDENTIALS: /usr/src/stock-scaper
      ENV: development
      HTTP_PROXY: http://proxy:5566
      HTTPS_PROXY: http://proxy:5566
  scraper:
    build: .
    volumes:
      - .:/usr/src/stock-scaper
    depends_on:
      - worker
    env_file: .env
    environment:
      DATABASE_URL: postgres://stocks:password@db:5432/stocks
      RABBITMQ_URL: amqp://rabbit:stock@mq:5672
      GOOGLE_CREDENTIALS: /usr/src/stock-scaper
      ENV: development
      HTTP_PROXY: http://proxy:5566
      HTTPS_PROXY: http://proxy:5566
